version: '3'

services:
  client:
    build: ./fats-down-client
    command: npm run start
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FDApiUrl=server
    depends_on:
      - server

  server:
    build: ./fats-down-server
    command: npm run start
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - Port=3333
      - ClientUrl=http://localhost:8080
      - AccessSecret=gorguts
      - RefreshSecret=krallice
      - DbType=postgres
      - DbHost=db
      - DbPort=5432
      - DbDatabase=fats_down
      - DbUser=root
      - DbPassword=root
      - DbSynchronize=false
    depends_on:
      -  db

  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fats_down
    ports:
      - "5432:5432"
