version: '3'

services:
  client:
    container_name: fats-down-client
    build: ./fats-down-client
    command: npm run start
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FDApiUrl=http://localhost:3333
    depends_on:
      - server
    networks:
      - fats-down-network

  server:
    container_name: fats-down-server
    build: ./fats-down-server
    command: npm run start
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - Port=3333
      - ClientUrl=client
      - AccessSecret=gorguts
      - RefreshSecret=krallice
      - DbType=postgres
      - DbHost=db
      - DbPort=5432
      - DbDatabase=fats_down
      - DbUser=root
      - DbPassword=root
      - DbSynchronize=true
    depends_on:
      -  db
    networks:
      - fats-down-network

  db:
    container_name: fats-down-db
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fats_down
    volumes:
      - postgres_api:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fats-down-network

  nginx:
    image: nginx:stable-alpine
    container_name: fats-down-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - client
    networks:
      - fats-down-network

volumes:
  postgres_api:

networks:
  fats-down-network:
    driver: bridge
